# SPDX-FileCopyrightText: 2019-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

linters:
  enable:
    - gofmt
    - gocyclo
    - revive
    - misspell
    - typecheck
    - errcheck
    - dogsled
    - unconvert
    - nakedret
    - exportloopref
linters-settings:
  staticcheck:
    checks:
      - '-SA1019'
issues:
  exclude-use-default: false
  exclude:
    - Error return value of `.*Close` is not checked
    - Error return value of `.*Flush` is not checked
    - Error return value of `.*Write` is not checked
    - Error return value of `` is not checked
    - 'package-comments:'
  exclude-rules:
    - path: cmd/gnmi_cli
      linters:
        - staticcheck
        - scopelint
