sudo: false

language: go

go:
  - '1.14.x'

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master



before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - pushd .. && git clone https://github.com/onosproject/build-tools.git && popd
  - export GOPRIVATE="github.com/onosproject/onos-e2t"

before_install:
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" && $TRAVIS_SECURE_ENV_VARS == "true" ]] ; then
         openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in .ssh/id_rsa.enc -out ~/.ssh/id_rsa -d &&
         chmod 600 ~/.ssh/id_rsa &&
         git config --global url."ssh://git@github.com/".insteadOf "https://github.com/";
       fi'

jobs:
  include:
    - stage: tests
      if: type == pull_request || fork == false
      script:

    - stage: release
      if: type != pull_request && fork == false
      script:
        - make coverage
        - bash ./build/bin/push-images
        - bash ../build-tools/release-merge-commit

